<a href="https://colab.research.google.com/github/omarammura-dev/Tensorflow/blob/main/00_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Tensors

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.15.0


# Creating Tensors with tf.constant()

In [ ]:
scaler = tf.constant(10)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=10>

#Check number of dimensions


In [ ]:
scaler.ndim


0

#Create a Vector

In [ ]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

#Create a Matrix

In [ ]:
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
an_matrix = tf.constant([[7.,6.],[4.,4.],[2.,1.]], dtype=tf.float16)
an_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[7., 6.],
       [4., 4.],
       [2., 1.]], dtype=float16)>

#With tf.variable()

In [ ]:
changable = tf.Variable([10,7]);
un_changable = tf.constant([10,7]);
un_changable,changable

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changable[0].assign(7)
changable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

#Create random tensors

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

#Shuffle the order of elements in a Tensor

In [ ]:
not_shuffled = tf.constant([[12,32],[242,21],[2131,232]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[  12,   32],
       [ 242,   21],
       [2131,  232]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2131,  232],
       [  12,   32],
       [ 242,   21]], dtype=int32)>

In [ ]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(23,31))

<tf.Tensor: shape=(23, 31), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 

In [ ]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

#Getting information from tensors

In [ ]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

#Indexing Tensors

In [ ]:
#Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Get the first element from each dimension fro each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#Create a rank 2 tensor (2-D)
rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
#Add in extra dimension to our rank 2 tensor
rank_3_tesnor = rank_2_tensor[...,tf.newaxis]
rank_3_tesnor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=-1)
rank_3_tesnor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

#Manipulating tensors(Operations)
**Basic Operations**

In [ ]:
#You can add values to a tensor using addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Multiplication also works !
tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
#Substraction
tensor -1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 6],
       [2, 3]], dtype=int32)>

In [ ]:
#TenorFlow built-in functions
tf.multiply(tensor,7)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[70, 49],
       [21, 28]], dtype=int32)>

#Matrix Multiplication

In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

#Changing the datatype of tensor

In [ ]:
#Create a new tensor with default datatype
B = tf.constant([8.1,2.3])
B.dtype

tf.float32

In [ ]:
C = tf.constant([8,2])
C.dtype

tf.int32

In [ ]:
#change from float32 to float16(reduced precision)
D = tf.cast(B,dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([8.1, 2.3], dtype=float16)>,
 tf.float16)

In [ ]:
#change from int32 to float33

E = tf.cast(C,dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([8., 2.], dtype=float32)>,
 tf.float32)

#Aggregating Tensors

In [ ]:
# Getting the absolute  values
D = tf.constant([-10,-7])
D


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-10,  -7], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

Getting throw the following forms of aggregation
* Get the maximum
* Get the minimum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
#Create a random tensor between 0 and 100 of size 50
S = tf.constant(np.random.randint(0,100,size=50), dtype=tf.float32)
S

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([92.,  9., 96., 86., 63., 48., 57., 74., 28., 74., 58., 55.,  8.,
       61., 31., 78., 71., 15., 11., 29.,  8., 51., 33., 82., 87., 32.,
       28., 97., 71., 19., 93., 79., 64., 51.,  1., 26., 58., 29., 15.,
       65., 72., 72., 91., 55.,  9., 25., 89., 83.,  6., 15.],
      dtype=float32)>

In [ ]:
tf.size(S), S.shape, S.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
#Get the min
tf.reduce_min(S)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [ ]:
#Get the max
tf.reduce_max(S)

<tf.Tensor: shape=(), dtype=float32, numpy=97.0>

In [ ]:
#Find the mean
tf.reduce_mean(S)

<tf.Tensor: shape=(), dtype=float32, numpy=51.0>

In [ ]:
#Find the sum
tf.reduce_sum(S)

<tf.Tensor: shape=(), dtype=float32, numpy=2550.0>

In [ ]:
#Find the variance
tf.math.reduce_variance(S)

<tf.Tensor: shape=(), dtype=float32, numpy=856.96>

In [ ]:
#Find the Standart deviation
tf.math.reduce_std(S)

<tf.Tensor: shape=(), dtype=float32, numpy=29.273878>

In [ ]:
#Find the positional min and max of a tensor
test_1 = tf.constant(np.random.randint(0,10000,size=150),dtype=tf.float32)
test_1

<tf.Tensor: shape=(150,), dtype=float32, numpy=
array([4920., 8218., 1802., 2198., 4926., 7631., 5192., 1749., 9991.,
       6091., 8507., 6743., 7027.,  875., 6880., 8530.,  637., 2082.,
        118., 8398., 4607., 6489., 2102., 8929., 9954., 6166., 3231.,
       2028., 6275., 4702., 2180., 7439., 5015., 9062., 2963.,  175.,
       7359., 1016., 7856., 1986.,    0., 7462., 1971., 6278., 7187.,
        184., 1886., 2680., 8730.,  995., 8541., 1988., 3820.,  885.,
        916., 7874., 6306., 5076., 5722., 8609., 3710., 9857., 5480.,
       4993., 5693., 2375., 2867., 8692.,   52., 9662., 5979., 3628.,
       7922., 9754., 7346., 5134., 8389., 6234., 7188., 3862., 6762.,
       6215., 9659., 6495., 5904., 9658., 7021.,   58., 1075., 2180.,
       6170., 1666., 9841., 7735., 9666., 1567., 1108., 9989., 9874.,
       8113., 8212., 7839., 9329., 7850., 5555., 5816.,  910., 4928.,
       3282., 7132., 7097., 4131., 1584., 2568., 8936., 9674.,  736.,
        363.,   18., 9719., 1202., 4729., 

In [ ]:
#Find the positional min
tf.math.argmin(test_1)

<tf.Tensor: shape=(), dtype=int64, numpy=40>

In [ ]:
#Find the positional Max
tf.math.argmax(test_1)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

#Squeezing a tesnsor

In [ ]:
#Create a tensor
tf.random.set_seed(42)
L = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
L

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
L_squeezed = tf.squeeze(L)
L_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

#One-Hot encoding tensors

In [ ]:
some_list = [0,1,2,3] #
# One hot encode
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#Specify custom values for one_hot encoding
tf.one_hot(some_list,depth=4,on_value="YEEEAH",off_value="Hmmm")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'YEEEAH', b'Hmmm', b'Hmmm', b'Hmmm'],
       [b'Hmmm', b'YEEEAH', b'Hmmm', b'Hmmm'],
       [b'Hmmm', b'Hmmm', b'YEEEAH', b'Hmmm'],
       [b'Hmmm', b'Hmmm', b'Hmmm', b'YEEEAH']], dtype=object)>

##Tensors with numPy

In [ ]:
# create a tensor from numpy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#Convert Tensor to numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

##Finding Access with GPUs

In [ ]:
tf.config.list_physical_devices()


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Thu Dec 14 18:41:36 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   70C    P0              30W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--